#!/usr/bin/env bash
# =============================================================================
# scripts/install-hooks.sh
# iNetPanel - Git Hooks Installer
# =============================================================================
# Run this once after cloning to enable automatic version bumping.
# Usage: bash scripts/install-hooks.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
HOOKS_DIR="$PROJECT_ROOT/.git/hooks"

if [[ ! -d "$HOOKS_DIR" ]]; then
    echo "[install-hooks] ERROR: Not a git repository or .git/hooks missing."
    echo "  Run: git init  first."
    exit 1
fi

# --- Write post-commit hook ---
HOOK_FILE="$HOOKS_DIR/post-commit"

cat > "$HOOK_FILE" << 'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh
# Bumps iNetPanel version by 0.001 after each commit

REPO_ROOT="$(git rev-parse --show-toplevel)"
BUMP_SCRIPT="$REPO_ROOT/scripts/version-bump.sh"

if [[ -x "$BUMP_SCRIPT" ]]; then
    bash "$BUMP_SCRIPT"
    # Amend the commit silently to include the bumped .env
    git add "$REPO_ROOT/TiCore/.env" 2>/dev/null || true
    GIT_EDITOR=true git commit --amend --no-edit --no-verify -q 2>/dev/null || true
fi
HOOK

chmod +x "$HOOK_FILE"
echo "[install-hooks] post-commit hook installed at: $HOOK_FILE"
echo "[install-hooks] Version will auto-increment by 0.001 after each commit."
